# To run this, name this file hello_world.yml and run the following in the same directory
# ansible-playbook hello_world.yml -i 'local,' --connection=local

- hosts:
  - local
  tasks:
  - debug:
      msg: "REQUEST_PATH == {{env.REQUEST_PATH}}"
  - name: "set flushed initial state"
    set_fact:
      flushed: false
- include: root.yml
  when:
    - env.REQUEST_PATH == "/"
    - flushed == false
- include: static.yml
  when: flushed == false
