# To run this, name this file hello_world.yml and run the following in the same directory
# ansible-playbook hello_world.yml -i 'local,' --connection=local

- hosts:
  - local
  tasks:
  - debug:
      msg: "REQUEST_PATH == {{env.REQUEST_PATH}} REQUEST_METHOD == {{env.REQUEST_METHOD}}"
  - name: "set flushed initial state"
    set_fact:
      flushed: false

  # cleanup body and header file if present
  - file:
      path: "{{bodyfile}}"
      state: absent
  - file:
      path: "{{headerfile}}"
      state: absent
### BEGIN CUSTOM ROUTES ###
- include: root.yml
  when:
    - env.REQUEST_PATH == "/"
    - env.REQUEST_METHOD == "GET"
    - flushed == false
# - include: 302test.yml
#   when:
#     - env.REQUEST_PATH == "/302"
#     - env.REQUEST_METHOD == "GET"
#     - flushed == false
- include: images.yml
  when:
    - env.REQUEST_PATH | search ("/images/")
    - env.REQUEST_METHOD == "GET"
    - flushed == false

- include: upload.yml
  when:
    - env.REQUEST_PATH == "/upload"
    - env.REQUEST_METHOD == "POST"
    - flushed == false

### END CUSTOM ROUTES ###

# default route is to fetch a static asset, or throw a 404 if not found
- include: static.yml
  when: flushed == false
